name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements_test.txt

    - name: Install package
      run: pip install .[tests] --no-deps

    - name: Run ruff
      run: |
        ruff check ./airbus_ship_detection
        ruff format --diff ./airbus_ship_detection

    - name: Type checking with mypy
      run: mypy ./airbus_ship_detection --install-types --non-interactive

    - name: Run tests
      run: pytest ./tests
